### ISSUE TITLE
vs_toolchain.py Visual Studio Version detection fails

### ISSUE THREAD

**Issue by DaCoolX** [ungoogled-software/ungoogled-chromium-windows#11]
[Log.txt](https://github.com/ungoogled-software/ungoogled-chromium-windows/files/3655487/Log.txt)
I notice it enters line 146 in vs_toolchain.py. I don't have DEPOT_TOOLS_WIN_TOOLCHAIN set.
I have Vis Studio 2019 Community.

Edit: It could be that I am an idiot who forgot to install depot_tools, if yes then this is a call for better logging of how much of an idiot I was and why

**Comment by tangalbert919** [comment]
Did you follow all of the instructions in the Visual Studio section [here](https://chromium.googlesource.com/chromium/src/+/refs/tags/77.0.3865.90/docs/windows_build_instructions.md#visual-studio)?

**Comment by DaCoolX** [comment]
depot_tools was missing, adding that solved this, paired with setting both env variables DEPOT_TOOLS_WIN_TOOLCHAIN = 0
and GYP_MSVS_VERSION = 2019

**Comment by Eloston** [comment]
Using `depot_tools` is not a supported use-case, and it violates the principle of not using Google binaries in the build. All you need to setup to build ungoogled-chromium should be explicitly and clearly described in the README.

We also don't want users to set environment variables unnecessarily, because that should be handled by `build.py`

We need to figure out the root cause of the exception and update our code accordingly. I don't have time to investigate this right now.

**Comment by DaCoolX** [comment]
Oh okay, the part about not wanting depot_tools should be explicitly mentioned.
I have been busy setting up a clean Windows build environment, to minimize other causes for issues.
I will see how far I can help to find, report and maybe solve them.

**Comment by r4sas** [comment]
Maybe can be useful: https://github.com/ungoogled-software/ungoogled-chromium-wiki/issues/5

**Comment by Eloston** [comment]
Let us know if you are still having troubles.

**Comment by DaCoolX** [comment]
Will do.
