### ISSUE TITLE
Installer binaries not running

### ISSUE THREAD

**Issue by sdfdger** [ungoogled-software/ungoogled-chromium-windows#160]
All of the [installer binaries](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/) I tried to run don't run even if running as an Administrator. The `.zip`s work fine. I occasionally got a "Windows protected your PC" warning, but I always clicked "Run anyway".

So far I tried:
- [103.0.5060.114-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/103.0.5060.114-1)
- [103.0.5060.53-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/103.0.5060.53-1)
- [102.0.5005.61](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/102.0.5005.61)
- [97.0.4692.71-1](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/97.0.4692.71-1)

Windows 10 64-bit (Administrator user)

**Comment by teeminus** [comment]
What do you mean by "not running"? The installer does not show an application window, it just unpacks the archive and exits.

**Comment by marcello-pietrobon** [comment]
> What do you mean by "not running"? The installer does not show an application window, it just unpacks the archive and exits.

If it works this way I believe it should be changed, or at least that, if ran from the CLI it should shows at least that it has completed its job.

I've not seen an installer that doesn't show in any way that is completing its job successfully. Ever.

If my opinion is incorrect please explain why.

By behaving this software this way I was lead to believe something was deeply wrong with my OS and I had to restore the OS from a previous image. I'm still currently slightly left with the doubt. This because being on Windows 10 I have to disable lots of stuff... I sleep better but I also need to know that the OS is still working correctly despite all things I've disabled.

Best Regards
