### ISSUE TITLE
setup.exe for ungoogled-chromium-windows has no gui

### ISSUE THREAD

**Issue by infinitegame111** [ungoogled-software/ungoogled-chromium-windows#238]
the setup file generated by ungoogled-chromium-windows right beside the .zip file also generated from py package.py has no gui. How can I get the setup to show the nice chrome installer gui

**Comment by infinitegame111** [comment]
note this installer does infact work and will install on another computer just no gui

**Comment by networkException** [comment]
I assume the gui installer is not part of chromium (only chrome), as such this is out of scope for the project

**Comment by infinitegame111** [comment]
Ok, is there a patch or anything? cause edge and brave both have gui installers using mini_installer's generated Setup.exe

**Comment by ansoni-san** [comment]
I believe the chrome installer is called Omaha. It also maintains the updates etc. 

You can use it if I recall correctly, but will need a specific server setup to communicate with it. 

https://github.com/google/omaha

I haven’t tried. We just built our own installer and update flow because we wanted our own flexibility.

**Comment by infinitegame111** [comment]
Ok thank you

**Comment by infinitegame111** [comment]
this has not worked I do believe there is a flag stopping gui from displaying can someone help me?
