### ISSUE TITLE
Error When Compiling 119.0.6045.159-1.1

### ISSUE THREAD

**Issue by FriedGenera** [ungoogled-software/ungoogled-chromium-windows#292]
I was able to compile [119.0.6045.123-1.1](https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/tag/119.0.6045.123-1.1) without any issues but when I try the latest release it gives me `ModuleNotFoundError: No module named 'httplib2'` I did `pip install httplib2` and it seems to have compiled, I was wondering if there was a better solution to this? Also does Ungoogled Chromium still require pypiwin32 to compile?

**Comment by teeminus** [comment]
`httplib2` is required since we switched to a new method to acquire the source code. Seems like I forgot to update the README with the new dependency. Thanks for the hint!

**Comment by FriedGenera** [comment]
I was also wondering, is there a way to remove this?
![experiment button](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/87927475/7ee08081-59d8-41fa-9182-d6bd747cd3bb)

**Comment by code-ga** [comment]
I have same error

**Comment by code-ga** [comment]
I had installed httplib2 
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/72681678/d7a53149-50e8-488a-a201-27a11466ddb2)
but when i run ```python build.py``` ( I use python because my python3 is in v3.11) and I have this error 
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/72681678/e5456972-d61d-4ab7-b89f-1fd337a3960d)
![image](https://github.com/ungoogled-software/ungoogled-chromium-windows/assets/72681678/4350999e-1e4a-4367-ad20-aef3ea1719ad)

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently and probably lost its significance — closing.
If you have any more information to add, let us know.
