### ISSUE TITLE
Gridinsoft detects ( Trojan.Heur!.02012822 ) on chrome.dll - from ( ungoogled-chromium version 119.0.6045.159-1.1_windows ) !

### ISSUE THREAD

**Issue by SteveJobsCousin** [ungoogled-software/ungoogled-chromium-windows#297]
i tested both " **chrome.dll** " from (google chrome) vs ( ungoogled-chromium-window ) on virustotal.com

- file hash : `18e5a31330f758001b88872f0d6870f819e89da0e947a32a8c08ed429aaf779c`

and only ( ungoogled-chromium-window  -> **chrome.dll** ) have shown a result of **( Trojan.Heur!.02012822 )**

 i'm trying to understand what really causes this, what code did we change to trigger it, and how we can fix it ?!

**Comment by PF4Public** [comment]
Is it a duplicate?

**Comment by teeminus** [comment]
@PF4Public It's a "duplicate" of https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/296 which I closed earlier (due to a misleading title and issue text).

@SteveJobsCousin Please refer to https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/146#issuecomment-1146628594

The issue reported is a false positive, we can't do anything about it. I will close this issue again as there is no solution for that. Other (ungoogled-) chromium builds are affected by this issue as well.
